apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongodb
spec:
  type: state.mongodb
  metadata:
    - name: host
      value: "localhost:27017"
    - name: dbName
      value: "demo-service"

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: "localhost:6379"
